### ISSUE TITLE
python_retro Running Mesen Core Error

### ISSUE THREAD

**Issue by one808** [lifning/python-retro#26]
File "D:\Python\Python37-32\lib\site-packages\py_retro\core.py", line 72, in __init__
    self.llw.set_video_refresh(self._video_refresh_wrapper)
OSError: exception: access violation reading 0x00000064
Exception ignored in: <function EmulatedSystem.__del__ at 0x03AF5C48>
Traceback (most recent call last):
  File "D:\Python\Python37-32\lib\site-packages\py_retro\core.py", line 86, in __del__
OSError: exception: access violation reading 0x00000000

**Comment by fregapple** [comment]
What core are you trying to use?
